name: DevOps-CI/CD
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout repo
      - name: Checkout Code
      - uses: actions/checkout@v3

      # install node
      - name: setup node
        uses: actions/setup-node@master
        with:
        node-version: ${{ matrix.node-version }}

       # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install
          npm ci 

      # build and test the apps     
      - name: build project
        run: |
          npm run build
          npm run test

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist